ingress:
  enabled: false
  tls: true
  ingressClassName: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
  hostname: deployments.cloud.eosc-siesta.eu
  userHostname: chart-example-user.local
  secretName: deployments.cloud.eosc-siesta.eu-tls
  hosts:
    - deployments.cloud.eosc-siesta.eu
  useCertManager: false
  certManagerClusterIssuer: ""
  useTlsSecret: true
