{{- if or .Values.autoscaling.enabled (not (.Values.global).suspend) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "library-chart.fullname" . }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: guacamole
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "library-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/guacamole-properties: {{ include (print $.Template.BasePath "/configmap-guacamole-properties.yaml") . | sha256sum }}
        checksum/postgres-secret: {{ include (print $.Template.BasePath "/secret-postgres.yaml") . | sha256sum }}
        {{- if .Values.extraEnvVars }}
        checksum/extraenv: {{ include (print $.Template.BasePath "/secret-extraenv.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "library-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: guacamole
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "library-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.initdb.enabled }}
      initContainers:
        - name: generate-initdb-sql
          {{- if .Values.service.image.custom.enabled }}
          image: {{ .Values.service.image.custom.version | quote }}
          {{- else }}
          image: {{ .Values.service.image.version | quote }}
          {{- end }}
          imagePullPolicy: {{ .Values.service.image.pullPolicy }}
          command: ["/bin/sh", "-lc"]
          args:
            - |
              set -e
              /opt/guacamole/bin/initdb.sh --postgresql > /work/initdb.sql
          volumeMounts:
            - name: initdb-work
              mountPath: /work
      {{- end }}
      containers:
        - name: postgres
          image: {{ .Values.postgres.image | quote }}
          imagePullPolicy: IfNotPresent
          env:
            - name: PGDATA
              value: {{ .Values.postgres.pgdata | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-postgres" (include "library-chart.fullname" .) }}
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-postgres" (include "library-chart.fullname" .) }}
                  key: POSTGRES_USER
          ports:
            - name: postgres
              containerPort: 5432
          resources:
            {{- toYaml .Values.resources.postgres | nindent 12 }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            {{- if .Values.initdb.enabled }}
            - name: initdb-work
              mountPath: /docker-entrypoint-initdb.d
            {{- end }}
        - name: guacd
          image: {{ .Values.guacd.image | quote }}
          imagePullPolicy: {{ .Values.service.image.pullPolicy }}
          ports:
            - name: guacd
              containerPort: 4822
          resources:
            {{- toYaml .Values.resources.guacd | nindent 12 }}
          {{- if or .Values.persistence.drive.enabled .Values.persistence.record.enabled }}
          volumeMounts:
            {{- if .Values.persistence.drive.enabled }}
            - name: drive
              mountPath: /drive
            {{- end }}
            {{- if .Values.persistence.record.enabled }}
            - name: record
              mountPath: /record
            {{- end }}
          {{- end }}
        - name: guacamole
          {{- if .Values.service.image.custom.enabled }}
          image: {{ .Values.service.image.custom.version | quote }}
          {{- else }}
          image: {{ .Values.service.image.version | quote }}
          {{- end }}
          imagePullPolicy: {{ .Values.service.image.pullPolicy }}
          env:
            - name: EXTENSIONS
              value: {{ .Values.guacamole.extensions | quote }}
            - name: GUACD_HOSTNAME
              value: "127.0.0.1"
            - name: POSTGRESQL_HOSTNAME
              value: "127.0.0.1"
            - name: POSTGRESQL_PORT
              value: "5432"
            - name: POSTGRESQL_DATABASE
              value: {{ .Values.postgres.database | quote }}
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-postgres" (include "library-chart.fullname" .) }}
                  key: POSTGRES_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-postgres" (include "library-chart.fullname" .) }}
                  key: POSTGRES_PASSWORD
          {{- if .Values.extraEnvVars }}
          envFrom:
            - secretRef:
                name: {{ include "library-chart.secretNameExtraEnv" . }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
          resources:
            {{- toYaml .Values.resources.guacamole | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence.drive.enabled }}
            - name: drive
              mountPath: /drive
            {{- end }}
            - name: guacamole-properties
              mountPath: /etc/guacamole/guacamole.properties
              subPath: guacamole.properties
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ printf "%s-postgres-data" (include "library-chart.fullname" .) }}
        {{- if .Values.initdb.enabled }}
        - name: initdb-work
          emptyDir: {}
        {{- end }}
        {{- if .Values.persistence.drive.enabled }}
        - name: drive
          persistentVolumeClaim:
            claimName: {{ printf "%s-guac-drive" (include "library-chart.fullname" .) }}
        {{- end }}
        {{- if .Values.persistence.record.enabled }}
        - name: record
          persistentVolumeClaim:
            claimName: {{ printf "%s-guac-record" (include "library-chart.fullname" .) }}
        {{- end }}
        - name: guacamole-properties
          configMap:
            name: {{ printf "%s-guacamole-properties" (include "library-chart.fullname" .) }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
