{{- if or .Values.autoscaling.enabled (not (.Values.global).suspend) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-guacd" (include "library-chart.fullname" .) }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: guacd
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: guacd
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: guacd
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "library-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: guacd
          image: {{ .Values.guacd.image | quote }}
          imagePullPolicy: {{ .Values.service.image.pullPolicy }}
          ports:
            - name: guacd
              containerPort: 4822
          resources:
            {{- toYaml .Values.resources.guacd | nindent 12 }}
          volumeMounts:
            - name: drive
              mountPath: /drive
            - name: record
              mountPath: /record
      volumes:
        - name: drive
          {{- if .Values.persistence.drive.enabled }}
          persistentVolumeClaim:
            claimName: {{ printf "%s-guac-drive" (include "library-chart.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: record
          {{- if .Values.persistence.record.enabled }}
          persistentVolumeClaim:
            claimName: {{ printf "%s-guac-record" (include "library-chart.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
