{{- if or .Values.autoscaling.enabled (not (.Values.global).suspend) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-postgres" (include "library-chart.fullname" .) }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
{{- end }}
