global:
  suspend: false

service:
  image:
    version: "accetto/ubuntu-vnc-xfce-g3:latest"
    pullPolicy: IfNotPresent
    custom:
      enabled: false
      version: "accetto/ubuntu-vnc-xfce-g3:latest"

security:
  password: "changeme"
  networkPolicy:
    enabled: false
    from: []
  allowlist:
    enabled: false
    ip: "0.0.0.0/0"

extraEnvVars: []

xfce:
  # Set the VNC password used by the desktop container.
  vncPassword: "changeme"
  # For accetto images, 5901 is VNC and 6901 is noVNC web UI.
  vncPort: 5901
  webPort: 6901

environment:
  user: onyxia
  group: users

replicaCount: 1

imagePullSecrets:
  - name: harbor-robot-secret

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

kubernetes:
  enabled: false
  role: "view"

podAnnotations: {}

podSecurityContext:
  fsGroup: 100

securityContext: {}

networking:
  type: ClusterIP
  clusterIP: None
  service:
    # noVNC web UI
    port: 6901
    targetPort: 6901
  # VNC port, useful for Guacamole testing and direct clients.
  user:
    enabled: true
    port: 5901
    ports: []

ingress:
  enabled: true
  tls: true
  ingressClassName: "nginx"
  annotations: []
  hostname: deployments.cloud.eosc-siesta.eu
  userHostname: chart-example-user.local
  secretName: deployments.cloud.eosc-siesta.eu-tls
  hosts:
    - deployments.cloud.eosc-siesta.eu
  useCertManager: false
  certManagerClusterIssuer: ""
  useTlsSecret: true

route:
  enabled: false
  annotations: []
  hostname: chart-example.local
  userHostname: chart-example-user.local
  tls:
    termination: edge
  wildcardPolicy: None

resources: {}

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 10Gi

nodeSelector:
  node.kubernetes.io/floating-ip: ""

tolerations: []
affinity: {}

userPreferences:
  darkMode: false
  language: "en"

autoscaling:
  enabled: false

openshiftSCC:
  enabled: false
  scc: ""

proxy:
  enabled: false
  noProxy: ""
  httpProxy: ""
  httpsProxy: ""

certificates: {}

message:
  fr: ""
  en: ""

repository:
  pipRepository: ''
  configMapName: ""
  condaRepository: ""
  rRepository: ""
  packageManagerUrl: ""
