{{- if (.Values.sharedS3).enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret-shared-s3" (include "library-chart.fullname" .) }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  SHARED_S3_ACCESS_KEY: {{ .Values.sharedS3.accessKey | quote }}
  SHARED_S3_SECRET_KEY: {{ .Values.sharedS3.secretKey | quote }}
{{- end }}
