{{- if or .Values.autoscaling.enabled (not (.Values.global).suspend) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secretvnc" (include "library-chart.fullname" .) }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  VNC_PASSWORD: {{ .Values.xfce.vncPassword | quote }}
{{- end }}
